import React from "react";
import ReactDOM from "react-dom/client";
import { Amplify } from "aws-amplify";
import App from "./App";
import { InvoiceWorkspace } from "./InvoiceWorkspace";
import "@aws-amplify/ui-react/styles.css";
import "./styles.css";

// `amplify_outputs.json` is generated by `npx ampx sandbox` (dev) or by
// Amplify Hosting at deploy time. Until then it's a `{}` stub: the app still
// runs fully in local/guest mode, just without the option to sign in and save
// to an account.
let configured = false;
try {
  const outputs = (await import("../amplify_outputs.json")).default;
  if (outputs && Object.keys(outputs).length > 0) {
    Amplify.configure(outputs);
    configured = true;
  }
} catch {
  configured = false;
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    {configured ? (
      <App />
    ) : (
      <InvoiceWorkspace authEnabled={false} authenticated={false} />
    )}
  </React.StrictMode>
);
