import React from "react";
import ReactDOM from "react-dom/client";
import { Amplify } from "aws-amplify";
import App from "./App";
import { SetupNotice } from "./SetupNotice";
import "@aws-amplify/ui-react/styles.css";
import "./styles.css";

// `amplify_outputs.json` is generated by `npx ampx sandbox` (dev) or by
// Amplify Hosting at deploy time. Until then it's a `{}` stub and we render
// SetupNotice instead of the app.
let configured = false;
try {
  const outputs = (await import("../amplify_outputs.json")).default;
  if (outputs && Object.keys(outputs).length > 0) {
    Amplify.configure(outputs);
    configured = true;
  }
} catch {
  configured = false;
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>{configured ? <App /> : <SetupNotice />}</React.StrictMode>
);
