/// <reference types="vite/client" />

declare module "*.css";

// Generated by `npx ampx sandbox` or by Amplify Hosting at deploy time.
// We import it dynamically and fall back to SetupNotice if the file is missing.
declare module "*amplify_outputs.json" {
  const value: Record<string, unknown>;
  export default value;
}
